// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqmokzfmioaqqlitlvnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbW9remZtaW9hcXFsaXRsdm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTU3NTAsImV4cCI6MjA2NzAzMTc1MH0.nfapWebe5PWhFUlwO14glcnItQC0F2uibLuKceKzCv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});