
name: Migrate Data and Deploy

on:
  workflow_dispatch:
    inputs:
      migrate_data:
        description: 'Run data migration'
        required: true
        default: 'true'
        type: boolean

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install @supabase/supabase-js dotenv
          
      - name: Run data migration
        if: ${{ github.event.inputs.migrate_data == 'true' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node scripts/migrateCountries.js
          
      - name: Notify completion
        run: |
          echo "✅ Migration completed successfully"
          echo "Countries data has been populated in Supabase"
