
name: Sync Data from Google Sheets

on:
  # Ejecución manual
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force complete resync'
        required: false
        default: 'false'
        type: boolean
  
  # Ejecución automática cada lunes a las 3 AM UTC
  schedule:
    - cron: '0 3 * * 1'

jobs:
  sync-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install papaparse @supabase/supabase-js
          
      - name: Run sync script
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "🚀 Starting sync process..."
          node scripts/syncFromSheet.js
          
      - name: Notify completion
        run: |
          echo "✅ Sync completed successfully"
          echo "📊 Data has been synchronized from Google Sheets to Supabase"
          echo "🕐 Next scheduled sync: $(date -d 'next monday 03:00' '+%Y-%m-%d %H:%M UTC')"
